package render

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lathe-cli/lathe/internal/sourceconfig"
	"github.com/lathe-cli/lathe/internal/specsync"
	"github.com/lathe-cli/lathe/pkg/config"
	"github.com/lathe-cli/lathe/pkg/runtime"
)

type SkillModule struct {
	Source *sourceconfig.Source
	State  *specsync.State
	Specs  []runtime.CommandSpec
}

type moduleRef struct {
	Module SkillModule
	File   string
	Flat   bool
}

const skillOwnerFile = ".lathe-skill"

func RenderSkillDirectory(root string, manifest *config.Manifest, modules []SkillModule) error {
	clean := filepath.Clean(root)
	if root == "" || clean == "." || clean == string(filepath.Separator) {
		return fmt.Errorf("invalid skill output directory %q", root)
	}
	if err := verifySkillDirectoryOwned(clean); err != nil {
		return err
	}
	refs, err := moduleReferences(manifest.CLI.CommandPath, modules)
	if err != nil {
		return err
	}
	if err := os.RemoveAll(clean); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(clean, "agents"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(clean, "references", "modules"), 0o755); err != nil {
		return err
	}
	files := map[string]string{
		filepath.Join(clean, "SKILL.md"):                 renderSkillMD(manifest, refs),
		filepath.Join(clean, skillOwnerFile):             "generated by lathe codegen; safe to remove and regenerate\n",
		filepath.Join(clean, "agents", "openai.yaml"):    renderOpenAIYAML(manifest),
		filepath.Join(clean, "references", "catalog.md"): renderCatalogReference(manifest),
	}
	for _, ref := range refs {
		files[filepath.Join(clean, "references", "modules", ref.File)] = renderModuleReference(manifest, ref.Module, ref.Flat)
	}
	for path, body := range files {
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d modules\n", clean, len(refs))
	return nil
}

func ValidateSkillIncludeRoot(skillRoot, includeRoot string) error {
	if includeRoot == "" {
		return nil
	}
	info, err := os.Stat(includeRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("skill include root %q does not exist", includeRoot)
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("skill include root %q is not a directory", includeRoot)
	}
	absRoot, err := filepath.Abs(skillRoot)
	if err != nil {
		return err
	}
	absInclude, err := filepath.Abs(includeRoot)
	if err != nil {
		return err
	}
	if pathContains(absRoot, absInclude) || pathContains(absInclude, absRoot) {
		return fmt.Errorf("skill include root %q must be outside skill root %q", includeRoot, skillRoot)
	}
	return nil
}

func ApplySkillIncludes(skillDir, includeRoot string) error {
	if includeRoot == "" {
		return nil
	}
	if err := ValidateSkillIncludeRoot(filepath.Dir(skillDir), includeRoot); err != nil {
		return err
	}
	return filepath.WalkDir(includeRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(includeRoot, path)
		if err != nil {
			return err
		}
		rel = filepath.Clean(rel)
		canAppend, err := skillIncludeFileCanAppend(rel)
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("skill include file %q is not a regular file", path)
		}
		add, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		target := filepath.Join(skillDir, rel)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		existing, err := os.ReadFile(target)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		if len(existing) > 0 && !canAppend {
			return fmt.Errorf("skill include file %q targets an existing non-appendable generated file", rel)
		}
		var merged []byte
		if len(existing) > 0 {
			merged = append(merged, existing...)
			if existing[len(existing)-1] != '\n' {
				merged = append(merged, '\n')
			}
			merged = append(merged, '\n')
		}
		merged = append(merged, add...)
		return os.WriteFile(target, merged, 0o644)
	})
}

func skillIncludeFileCanAppend(rel string) (bool, error) {
	slash := filepath.ToSlash(rel)
	switch {
	case slash == "SKILL.md":
		return true, nil
	case strings.HasPrefix(slash, "references/") && strings.HasSuffix(slash, ".md"):
		return true, nil
	case strings.HasPrefix(slash, "agents/"),
		strings.HasPrefix(slash, "assets/"),
		strings.HasPrefix(slash, "references/"),
		strings.HasPrefix(slash, "scripts/"):
		return false, nil
	default:
		return false, fmt.Errorf("skill include file %q must target SKILL.md, agents/, assets/, references/, or scripts/", rel)
	}
}

func pathContains(base, path string) bool {
	rel, err := filepath.Rel(base, path)
	if err != nil {
		return false
	}
	return filepath.IsLocal(rel)
}

func verifySkillDirectoryOwned(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("skill output path %q exists and is not a directory", root)
	}
	if _, err := os.Stat(filepath.Join(root, skillOwnerFile)); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("refusing to remove existing non-lathe skill directory %q", root)
		}
		return err
	}
	return nil
}

func SkillDirName(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == '-' || r == '_' || r == ' ' || r == '.':
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "cli"
	}
	return out
}

func moduleReferences(policy string, modules []SkillModule) ([]moduleRef, error) {
	mods := append([]SkillModule(nil), modules...)
	sort.SliceStable(mods, func(i, j int) bool {
		return moduleName(mods[i]) < moduleName(mods[j])
	})
	used := map[string]int{}
	refs := make([]moduleRef, 0, len(mods))
	for _, mod := range mods {
		flat, err := ResolveFlatCommandPath(policy, len(mods), mod.Specs)
		if err != nil {
			return nil, err
		}
		base := SkillDirName(moduleName(mod))
		used[base]++
		fileBase := base
		if used[base] > 1 {
			fileBase = fmt.Sprintf("%s-%d", base, used[base])
		}
		refs = append(refs, moduleRef{Module: mod, File: fileBase + ".md", Flat: flat})
	}
	return refs, nil
}

func renderSkillMD(manifest *config.Manifest, refs []moduleRef) string {
	cli := manifest.CLI.Name
	skill := SkillDirName(cli)
	var b strings.Builder
	fmt.Fprintf(&b, "---\nname: %s\ndescription: >\n  Use when operating the %s generated CLI. Discover commands, inspect parameters,\n  check auth state, and execute API operations safely.\n---\n\n", skill, cli)
	fmt.Fprintf(&b, "# %s CLI\n\n", cli)
	fmt.Fprintf(&b, "Use this skill when a user asks you to operate `%s`, inspect its API commands, or find the right generated command for an API task.\n\n", cli)
	b.WriteString("## Workflow\n\n")
	fmt.Fprintf(&b, "1. Search for candidates with `%s search \"<intent>\" --json`; use `--limit` when needed. Search is only candidate discovery.\n", cli)
	fmt.Fprintf(&b, "2. Inspect the exact command with `%s commands show <path...> --json` before executing an unfamiliar command.\n", cli)
	fmt.Fprintf(&b, "3. If the command detail has `auth.required=true`, run `%s auth status --hostname <host>` before execution. If it is not logged in, stop and ask the user to authenticate.\n", cli)
	fmt.Fprintf(&b, "4. Execute only after flags, body, auth, HTTP path, and output hints are clear from `commands show`.\n\n")
	b.WriteString("## General Commands\n\n")
	fmt.Fprintf(&b, "- `%s commands --json`: full generated command catalog.\n", cli)
	fmt.Fprintf(&b, "- `%s commands --include-hidden --json`: include hidden generated commands.\n", cli)
	fmt.Fprintf(&b, "- `%s commands show <path...> --json`: source of truth for one command.\n", cli)
	fmt.Fprintf(&b, "- `%s commands schema --json`: catalog schema version for parser compatibility.\n", cli)
	fmt.Fprintf(&b, "- `%s search \"<intent>\" --json`: ranked candidate commands.\n\n", cli)
	b.WriteString("## References\n\n")
	b.WriteString("- Read `references/catalog.md` for the command discovery protocol and catalog field meanings.\n")
	for _, ref := range refs {
		fmt.Fprintf(&b, "- Read `references/modules/%s` for the `%s` module command index.\n", ref.File, moduleName(ref.Module))
	}
	b.WriteString("\n## Rules\n\n")
	b.WriteString("- Do not guess flags or request body shape from command names.\n")
	b.WriteString("- Do not execute directly from search results; confirm with `commands show` first.\n")
	b.WriteString("- Prefer `-o json` for machine-readable command output unless the user asks for human-readable output.\n")
	b.WriteString("- Use `--file`, `--set`, or `--set-str` for JSON request bodies according to `commands show` body requirements.\n")
	return b.String()
}

func renderOpenAIYAML(manifest *config.Manifest) string {
	cli := manifest.CLI.Name
	skill := SkillDirName(cli)
	return fmt.Sprintf("interface:\n  display_name: %s\n  short_description: %s\n  default_prompt: %s\n",
		yamlString(cli+" CLI"),
		yamlString("Use the "+cli+" generated CLI"),
		yamlString("Use $"+skill+" to find and run the right "+cli+" command."),
	)
}

func renderCatalogReference(manifest *config.Manifest) string {
	cli := manifest.CLI.Name
	var b strings.Builder
	b.WriteString("# Catalog Protocol\n\n")
	b.WriteString("Use the runtime catalog as the source of truth. Generated references are a fast index; command execution details come from the CLI itself.\n\n")
	b.WriteString("## Search\n\n")
	fmt.Fprintf(&b, "Run `%s search \"<intent>\" --json` to find candidate commands. Use `--limit` to control result count. Treat search output as candidates only.\n\n", cli)
	b.WriteString("## Full Catalog\n\n")
	fmt.Fprintf(&b, "Run `%s commands --json` to inspect the generated command catalog. Use `--include-hidden` only when hidden commands are relevant.\n\n", cli)
	b.WriteString("Key fields:\n\n")
	b.WriteString("- `path`: command path to pass to `commands show` or execute after the CLI name.\n")
	b.WriteString("- `http`: HTTP method and path template.\n")
	b.WriteString("- `flags`: CLI flags, parameter location, type, required state, defaults, enum values, format, and help.\n")
	b.WriteString("- `body`: request body requirement and media type.\n")
	b.WriteString("- `auth`: whether auth is required and which scopes are declared.\n")
	b.WriteString("- `output`: list path, default columns, response media type, pagination, and streaming hints.\n")
	b.WriteString("- `notes`, `prerequisites`, and `known_errors`: overlay-provided operation context that is not inferred from the API spec.\n\n")
	b.WriteString("## Command Detail\n\n")
	fmt.Fprintf(&b, "Run `%s commands show <path...> --json` before executing an unfamiliar command. This is the source of truth for flags, body, auth, HTTP path, and output hints.\n\n", cli)
	b.WriteString("## Schema\n\n")
	fmt.Fprintf(&b, "Run `%s commands schema --json` to read the catalog schema version before parsing catalog JSON with durable tooling.\n\n", cli)
	b.WriteString("## Request Bodies\n\n")
	b.WriteString("- `--file path`: read a JSON body from a file.\n")
	b.WriteString("- `--file -`: read a JSON body from stdin.\n")
	b.WriteString("- `--set key.path=value`: build JSON with type inference for booleans, null, integers, and floats.\n")
	b.WriteString("- `--set-str key.path=value`: build JSON while forcing the value to remain a string.\n\n")
	b.WriteString("## Output\n\n")
	b.WriteString("Use `-o json` for machine-readable command output. Other supported formats are `table`, `yaml`, and `raw`.\n\n")
	b.WriteString("## Auth\n\n")
	fmt.Fprintf(&b, "If command detail returns `auth.required=true`, run `%s auth status --hostname <host>` before execution. If no matching host is logged in, stop and ask the user to authenticate.\n", cli)
	return b.String()
}

func renderModuleReference(manifest *config.Manifest, mod SkillModule, flat bool) string {
	cli := manifest.CLI.Name
	specs := visibleSpecs(mod.Specs)
	var b strings.Builder
	fmt.Fprintf(&b, "# Module `%s`\n\n", moduleName(mod))
	b.WriteString("## Source\n\n")
	if mod.Source != nil {
		fmt.Fprintf(&b, "- Backend: `%s`\n", mod.Source.Backend)
		fmt.Fprintf(&b, "- Repository: %s\n", valueOrUnknown(mod.Source.RepoURL))
		fmt.Fprintf(&b, "- Pinned tag: `%s`\n", valueOrUnknown(mod.Source.PinnedTag))
		for _, line := range sourceInputs(mod.Source) {
			fmt.Fprintf(&b, "- %s\n", line)
		}
	}
	if mod.State != nil && mod.State.ResolvedSHA != "" {
		fmt.Fprintf(&b, "- Resolved SHA: `%s`\n", mod.State.ResolvedSHA)
	}
	b.WriteString("\n")
	if len(specs) == 0 {
		b.WriteString("No visible generated commands. Use `commands --include-hidden --json` if hidden commands are relevant.\n")
		return b.String()
	}
	groups := groupSpecs(specs)
	module := moduleName(mod)
	for _, group := range sortedKeys(groups) {
		fmt.Fprintf(&b, "## %s\n\n", group)
		for _, spec := range groups[group] {
			path := commandPath(cli, module, spec, flat)
			fmt.Fprintf(&b, "### `%s`\n\n", strings.Join(path, " "))
			if spec.Short != "" {
				fmt.Fprintf(&b, "- Summary: %s\n", oneLine(spec.Short))
			}
			fmt.Fprintf(&b, "- HTTP: `%s %s`\n", spec.Method, spec.PathTpl)
			fmt.Fprintf(&b, "- Auth: %s\n", authSummary(spec.Security))
			fmt.Fprintf(&b, "- Body: %s\n", bodySummary(spec.RequestBody))
			if len(spec.Params) == 0 {
				b.WriteString("- Flags: none\n")
			} else {
				b.WriteString("- Flags:\n")
				for _, p := range spec.Params {
					req := ""
					if p.Required {
						req = ", required"
					}
					def := ""
					if p.Default != "" {
						def = fmt.Sprintf(", default `%s`", p.Default)
					}
					format := ""
					if p.Format != "" {
						format = ", " + p.Format
					}
					enum := ""
					if len(p.Enum) > 0 {
						enum = ", one of: " + strings.Join(p.Enum, "|")
					}
					deprecated := ""
					if p.Deprecated {
						deprecated = ", deprecated"
					}
					fmt.Fprintf(&b, "  - `--%s` (%s%s%s%s%s%s): %s\n", p.Flag, p.In, req, def, format, enum, deprecated, oneLine(stripHelpMeta(p.Help)))
				}

			}
			if out := outputSummary(spec.Output); out != "" {
				fmt.Fprintf(&b, "- Output: %s\n", out)
			}
			writeOperationContext(&b, spec)
			if spec.Example != "" {
				writeExample(&b, commandExample(spec.Example, cli, module, spec, flat))
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

func commandExample(example, cli, module string, spec runtime.CommandSpec, flat bool) string {
	newPath := strings.Join(commandPath(cli, module, spec, true), " ")
	oldPaths := []string{strings.Join(legacyCommandPath(cli, module, spec, flat), " ")}
	if !flat {
		newPath = strings.Join(commandPath(cli, module, spec, false), " ")
	} else {
		oldPaths = append([]string{
			strings.Join(commandPath(cli, module, spec, false), " "),
			strings.Join(legacyCommandPath(cli, module, spec, false), " "),
		}, oldPaths...)
	}
	for _, oldPath := range oldPaths {
		if oldPath != newPath {
			example = strings.ReplaceAll(example, oldPath, newPath)
		}
	}
	return example
}

func writeOperationContext(b *strings.Builder, spec runtime.CommandSpec) {
	writeStringList(b, "Notes", spec.Notes)
	writeStringList(b, "Prerequisites", spec.Prerequisites)
	if len(spec.KnownErrors) == 0 {
		return
	}
	b.WriteString("- Known errors:\n")
	for _, err := range spec.KnownErrors {
		label := "unspecified status"
		if err.Status != 0 {
			label = fmt.Sprintf("HTTP %d", err.Status)
		}
		cause := oneLine(err.Cause)
		if cause == "" {
			fmt.Fprintf(b, "  - %s\n", label)
			continue
		}
		fmt.Fprintf(b, "  - %s: %s\n", label, cause)
	}
}

func writeStringList(b *strings.Builder, label string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "- %s:\n", label)
	for _, value := range values {
		fmt.Fprintf(b, "  - %s\n", oneLine(value))
	}
}

func writeExample(b *strings.Builder, example string) {
	text := strings.TrimRight(example, "\n")
	if strings.Contains(text, "\n") {
		fence := markdownFence(text)
		fmt.Fprintf(b, "- Example:\n\n%s\n%s\n%s\n", fence, text, fence)
		return
	}
	fmt.Fprintf(b, "- Example: `%s`\n", strings.ReplaceAll(oneLine(text), "`", "'"))
}

func markdownFence(text string) string {
	fence := "```"
	for strings.Contains(text, fence) {
		fence += "`"
	}
	return fence
}

func visibleSpecs(specs []runtime.CommandSpec) []runtime.CommandSpec {
	out := make([]runtime.CommandSpec, 0, len(specs))
	for _, spec := range specs {
		if !spec.Hidden {
			out = append(out, spec)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Group == out[j].Group {
			return out[i].Use < out[j].Use
		}
		return out[i].Group < out[j].Group
	})
	return out
}

func groupSpecs(specs []runtime.CommandSpec) map[string][]runtime.CommandSpec {
	out := map[string][]runtime.CommandSpec{}
	for _, spec := range specs {
		group := spec.Group
		if group == "" {
			group = "Commands"
		}
		out[group] = append(out[group], spec)
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func moduleName(mod SkillModule) string {
	if mod.Source != nil && mod.Source.DisplayName != "" {
		return mod.Source.DisplayName
	}
	if mod.Source != nil && mod.Source.Name != "" {
		return mod.Source.Name
	}
	if mod.State != nil && mod.State.Source != "" {
		return mod.State.Source
	}
	return "module"
}

func sourceInputs(src *sourceconfig.Source) []string {
	switch src.Backend {
	case sourceconfig.BackendSwagger:
		return []string{"Files: `" + strings.Join(src.Swagger.Files, "`, `") + "`"}
	case sourceconfig.BackendOpenAPI3:
		return []string{"Files: `" + strings.Join(src.OpenAPI3.Files, "`, `") + "`"}
	case sourceconfig.BackendProto:
		lines := []string{"Entries: `" + strings.Join(src.Proto.Entries, "`, `") + "`"}
		if len(src.Proto.ImportRoots) > 0 {
			lines = append(lines, "Import roots: `"+strings.Join(src.Proto.ImportRoots, "`, `")+"`")
		}
		if len(src.Proto.Staging) > 0 {
			lines = append(lines, fmt.Sprintf("Staging entries: `%d`", len(src.Proto.Staging)))
		}
		return lines
	case sourceconfig.BackendGraphQL:
		if src.GraphQL == nil {
			return nil
		}
		lines := []string{"Schema: `" + src.GraphQL.Schema + "`"}
		if src.GraphQL.Expose != nil {
			if len(src.GraphQL.Expose.Queries) > 0 {
				lines = append(lines, "Expose queries: `"+strings.Join(src.GraphQL.Expose.Queries, "`, `")+"`")
			}
			if len(src.GraphQL.Expose.Mutations) > 0 {
				lines = append(lines, "Expose mutations: `"+strings.Join(src.GraphQL.Expose.Mutations, "`, `")+"`")
			}
		}
		if len(src.GraphQL.Groups) > 0 {
			lines = append(lines, fmt.Sprintf("Group policies: `%d`", len(src.GraphQL.Groups)))
		}
		if len(src.GraphQL.Output) > 0 {
			lines = append(lines, fmt.Sprintf("Output policies: `%d`", len(src.GraphQL.Output)))
		}
		if src.GraphQL.Selection != nil {
			parts := make([]string, 0, 2)
			if src.GraphQL.Selection.MaxDepth != nil {
				parts = append(parts, fmt.Sprintf("max depth `%d`", *src.GraphQL.Selection.MaxDepth))
			}
			if len(src.GraphQL.Selection.Prune) > 0 {
				parts = append(parts, fmt.Sprintf("prune rules `%d`", len(src.GraphQL.Selection.Prune)))
			}
			if len(parts) > 0 {
				lines = append(lines, "Selection policy: "+strings.Join(parts, "; "))
			}
		}
		return lines
	default:
		return nil
	}
}

func commandPath(cli, module string, spec runtime.CommandSpec, flat bool) []string {
	path := []string{cli}
	if !flat {
		path = append(path, module)
	}
	if group := rootCommandName(spec.Group); group != "" {
		path = append(path, group)
	}
	return append(path, spec.Use)
}

func legacyCommandPath(cli, module string, spec runtime.CommandSpec, flat bool) []string {
	path := []string{cli}
	if !flat {
		path = append(path, module)
	}
	if spec.Group != "" {
		path = append(path, strings.ToLower(spec.Group))
	}
	return append(path, spec.Use)
}

func authSummary(security *runtime.SecurityHint) string {
	if security != nil && security.Public {
		return "public"
	}
	if security != nil && len(security.Scopes) > 0 {
		return "required; scopes: `" + strings.Join(security.Scopes, "`, `") + "`"
	}
	return "required"
}

func bodySummary(body *runtime.RequestBody) string {
	if body == nil {
		return "none"
	}
	state := "optional"
	if body.Required {
		state = "required"
	}
	if body.Template != "" {
		merge := body.MergePath
		if merge == "" {
			merge = "the document root"
		}
		return state + "; templated body, set inputs under `" + merge + "` with --set/--set-str/--file"
	}
	if body.MediaType != "" {
		return state + "; media type `" + body.MediaType + "`"
	}
	return state
}

func outputSummary(out runtime.OutputHints) string {
	parts := make([]string, 0, 5)
	if out.ListPath != "" {
		parts = append(parts, "list path `"+out.ListPath+"`")
	}
	if len(out.DefaultColumns) > 0 {
		parts = append(parts, "columns `"+strings.Join(out.DefaultColumns, "`, `")+"`")
	}
	if out.ResponseMediaType != "" {
		parts = append(parts, "response media `"+out.ResponseMediaType+"`")
	}
	if out.Pagination != nil {
		parts = append(parts, "pagination `"+out.Pagination.Strategy+"`")
	}
	if out.Streaming != nil {
		parts = append(parts, "streaming `"+out.Streaming.Strategy+"`")
	}
	return strings.Join(parts, "; ")
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// stripHelpMeta removes the trailing " (...)" annotation that helpText() appends,
// so callers that render the metadata separately don't produce duplicates.
func stripHelpMeta(s string) string {
	if i := strings.LastIndex(s, " ("); i >= 0 && strings.HasSuffix(s, ")") {
		return s[:i]
	}
	return s
}

func valueOrUnknown(s string) string {
	if s == "" {
		return "`unknown`"
	}
	return s
}

func yamlString(s string) string {
	raw, err := json.Marshal(s)
	if err != nil {
		return `""`
	}
	return string(raw)
}
