package render

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lathe-cli/lathe/internal/sourceconfig"
	"github.com/lathe-cli/lathe/internal/specsync"
	"github.com/lathe-cli/lathe/pkg/config"
	"github.com/lathe-cli/lathe/pkg/runtime"
)

type SkillModule struct {
	Source *sourceconfig.Source
	State  *specsync.State
	Specs  []runtime.CommandSpec
}

type moduleRef struct {
	Module SkillModule
	File   string
	Flat   bool
}

const skillOwnerFile = ".lathe-skill"

type skillFile struct {
	body []byte
	mode fs.FileMode
}

func RenderSkillDirectory(root string, manifest *config.Manifest, modules []SkillModule) error {
	return renderSkillDirectory(root, manifest, modules, SkillInclude{})
}

func RenderSkillDirectoryWithInclude(root string, manifest *config.Manifest, modules []SkillModule, include SkillInclude) error {
	return renderSkillDirectory(root, manifest, modules, include)
}

func renderSkillDirectory(root string, manifest *config.Manifest, modules []SkillModule, include SkillInclude) error {
	clean := filepath.Clean(root)
	if root == "" || clean == "." || clean == string(filepath.Separator) {
		return fmt.Errorf("invalid skill output directory %q", root)
	}
	if err := verifySkillDirectoryOwned(clean); err != nil {
		return err
	}
	include, err := normalizeSkillInclude(include)
	if err != nil {
		return err
	}
	if err := ValidateSkillIncludeRoot(filepath.Dir(clean), include.Path); err != nil {
		return err
	}
	allRefs, err := moduleReferences(manifest.CLI.CommandPath, modules)
	if err != nil {
		return err
	}
	allGenerated := renderSkillFiles(manifest, allRefs)
	if err := validateSkillIncludePolicy(include, allGenerated); err != nil {
		return err
	}
	refs := filterOmittedModuleRefs(allRefs, include)
	files := renderSkillFiles(manifest, refs)
	if err := mergeSkillIncludes(files, allGenerated, include); err != nil {
		return err
	}
	if err := writeSkillDirectory(clean, files); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s: %d modules\n", clean, len(refs))
	return nil
}

func renderSkillFiles(manifest *config.Manifest, refs []moduleRef) map[string]skillFile {
	files := map[string]skillFile{
		"SKILL.md":              newSkillFile(renderSkillMD(manifest, refs)),
		skillOwnerFile:          newSkillFile("generated by lathe codegen; safe to remove and regenerate\n"),
		"agents/openai.yaml":    newSkillFile(renderOpenAIYAML(manifest)),
		"references/catalog.md": newSkillFile(renderCatalogReference(manifest)),
	}
	for _, ref := range refs {
		files["references/modules/"+ref.File] = newSkillFile(renderModuleReference(manifest, ref.Module, ref.Flat))
	}
	return files
}

func newSkillFile(body string) skillFile {
	return skillFile{body: []byte(body), mode: 0o644}
}

func writeSkillDirectory(root string, files map[string]skillFile) error {
	parent := filepath.Dir(root)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return err
	}
	tmp, err := os.MkdirTemp(parent, "."+filepath.Base(root)+".tmp-")
	if err != nil {
		return err
	}
	removeTmp := true
	defer func() {
		if removeTmp {
			_ = os.RemoveAll(tmp)
		}
	}()
	for rel, file := range files {
		target := filepath.Join(tmp, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, file.body, file.mode); err != nil {
			return err
		}
	}
	if err := os.RemoveAll(root); err != nil {
		return err
	}
	if err := os.Rename(tmp, root); err != nil {
		return err
	}
	removeTmp = false
	return nil
}

func verifySkillDirectoryOwned(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("skill output path %q exists and is not a directory", root)
	}
	if _, err := os.Stat(filepath.Join(root, skillOwnerFile)); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("refusing to remove existing non-lathe skill directory %q", root)
		}
		return err
	}
	return nil
}

func SkillDirName(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(strings.TrimSpace(name)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == '-' || r == '_' || r == ' ' || r == '.':
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "cli"
	}
	return out
}

func moduleReferences(policy string, modules []SkillModule) ([]moduleRef, error) {
	mods := append([]SkillModule(nil), modules...)
	sort.SliceStable(mods, func(i, j int) bool {
		return moduleName(mods[i]) < moduleName(mods[j])
	})
	used := map[string]int{}
	refs := make([]moduleRef, 0, len(mods))
	for _, mod := range mods {
		flat, err := ResolveFlatCommandPath(policy, len(mods), mod.Specs)
		if err != nil {
			return nil, err
		}
		base := SkillDirName(moduleName(mod))
		used[base]++
		fileBase := base
		if used[base] > 1 {
			fileBase = fmt.Sprintf("%s-%d", base, used[base])
		}
		refs = append(refs, moduleRef{Module: mod, File: fileBase + ".md", Flat: flat})
	}
	return refs, nil
}
