package render

import (
	"text/template"
)

var moduleTmpl = template.Must(template.New("gen").Funcs(template.FuncMap{"literal": goLiteral}).Parse(`// Code generated by lathe codegen. DO NOT EDIT.

package {{.Module}}

import (
    "github.com/spf13/cobra"
    "{{.RuntimePkg}}"
)

const generatedSchemaVersion = {{.SchemaVersion}}

func Mount(root *cobra.Command) error {
    if err := runtime.AssertSchema(generatedSchemaVersion); err != nil {
        return err
    }
    return runtime.Build(root, {{printf "%q" .CLIName}}, Specs)
}

func MountFlat(root *cobra.Command) error {
    if err := runtime.AssertSchema(generatedSchemaVersion); err != nil {
        return err
    }
    return runtime.BuildFlat(root, {{printf "%q" .CLIName}}, Specs)
}

var Specs = []runtime.CommandSpec{
{{- range .Ops}}
    {{literal .}},
{{- end}}
}
`))

var modulesTmpl = template.Must(template.New("modules").Parse(`// Code generated by lathe codegen. DO NOT EDIT.

package generated

import (
	latheruntime "github.com/lathe-cli/lathe/pkg/runtime"
	"github.com/spf13/cobra"
{{- if .SkillBundle}}
	lathebundle "github.com/lathe-cli/lathe/pkg/skillbundle"
{{- end}}

{{- range .Modules}}
	{{.Name}} "{{$.Prefix}}{{.Name}}"
{{- end}}
{{- if .Workflows}}
	lathegeneratedworkflows "{{$.Prefix}}workflows"
{{- end}}
{{- if .SkillBundle}}
	lathegeneratedskillbundle "{{$.Prefix}}skillbundle"
{{- end}}
)

var latheSourceProvenance = []latheruntime.SourceProvenance{
{{- range .Sources}}
	{ID: {{printf "%q" .ID}}, Backend: {{printf "%q" .Backend}}, Kind: {{printf "%q" .Kind}}, RepoURL: {{printf "%q" .RepoURL}}, PinnedTag: {{printf "%q" .PinnedTag}}, ResolvedSHA: {{printf "%q" .ResolvedSHA}}, Reproducible: {{.Reproducible}}},
{{- end}}
}

func Mount(root *cobra.Command) error {
	return MountModules(root)
}

func MountModules(root *cobra.Command) error {
	latheruntime.AttachSourceProvenance(root, latheSourceProvenance)
{{- range .Modules}}
	if err := {{.Name}}.{{if .Flat}}MountFlat{{else}}Mount{{end}}(root); err != nil {
		return err
	}
{{- end}}
{{- if .Workflows}}
	if err := lathegeneratedworkflows.Mount(root); err != nil {
		return err
	}
{{- end}}
{{- if .SkillBundle}}
	lathebundle.Mount(root, lathegeneratedskillbundle.FS, lathegeneratedskillbundle.Root)
{{- end}}
	return nil
}
`))

var workflowsTmpl = template.Must(template.New("workflows").Funcs(template.FuncMap{
	"literal": goLiteral,
}).Parse(`// Code generated by lathe codegen. DO NOT EDIT.

package workflows

import (
	"github.com/spf13/cobra"

	"{{.RuntimePkg}}"
)

func Mount(root *cobra.Command) error {
	return runtime.BuildWorkflows(root, Specs)
}

var Specs = []runtime.WorkflowSpec{
{{- range .Specs}}
	{{literal .}},
{{- end}}
}
`))

var skillBundleTmpl = template.Must(template.New("skillbundle").Parse(`// Code generated by lathe codegen. DO NOT EDIT.

package skillbundle

import "embed"

const Root = {{printf "%q" .Root}}

//go:embed {{.Root}}/**
var FS embed.FS
`))
